# Generated by Django 5.2 on 2025-08-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_desk"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="desk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.desk",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(default="employee", max_length=50),
        ),
    ]
